#Sets website theme
theme: minima

#Set title
title: Andrew Scheiner's Website

#Set author
author: 
  name: Andrew Scheiner
  email: scheinera53@gmail.com

#Set description:
description: My personal wesbite to showcase my projects, skills, and interests in computer science, data analytics, development, visualization, sports, and more!

#Social links:
minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,         user_url: "https://github.com/Baseballfan5303" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/andrew-scheiner-8827b9233/" }
  
#include folders on build
include:
  - "_includes"
  - "_layouts"
