#Sets website theme
theme: minima

#Set title
title: Andrew Scheiner's Website

#Add social links to footer
minima:
    social_links:
        - { platform: github,         user_url: "https://github.com/Baseballfan5303" }
        - { platform: linkedin,       user_url: "https://www.linkedin.com/in/andrew-scheiner-8827b9233/" }

#Do not include excerpts
show_excerpts: false
