#Sets website theme
theme: minima

#Set title
title: Andrew Scheiner's Website

#Set author
author: Andrew Scheiner

#Add social links to footer
social-network-links:
  github: Baseballfan5303
  linkedin: https://www.linkedin.com/in/andrew-scheiner-8827b9233/

#Do not include excerpts
show_excerpts: false
