#Sets website theme
theme: minima

#Set title
title: Andrew Scheiner's Website

#Set author
author: Andrew Scheiner

#Set description:
description: A website to showcase my projects, skills, and interests in computer science, data analytics, development, sports, and more!
